//! Typed publication / subscription wrappers around PX4 uORB.
//!
//! ```ignore
//! use px4_uorb::{Publication, Subscription};
//! use my_msgs::{sensor_gyro, SensorGyro};   // generated by #[px4_message]
//!
//! static PUB: Publication<sensor_gyro> = Publication::new();
//!
//! #[px4_workqueue::task(wq = "rate_ctrl")]
//! async fn publisher() {
//!     let s = SensorGyro { /* ... */ };
//!     PUB.publish(&s).unwrap();
//! }
//!
//! #[px4_workqueue::task(wq = "rate_ctrl")]
//! async fn subscriber() {
//!     let sub = Subscription::<sensor_gyro>::new();
//!     loop {
//!         let msg: SensorGyro = sub.recv().await;
//!         // …
//!     }
//! }
//! ```

#![cfg_attr(not(feature = "std"), no_std)]

mod ffi;
mod pub_;
mod sub;
mod topic;

pub use pub_::{PubError, Publication};
pub use sub::{Recv, Subscription};
pub use topic::{OrbMetadata, UorbTopic};

#[cfg(feature = "std")]
pub use ffi::mock::_reset_broker;
